### PR TITLE
trivial: fixing multipanel carousel

### LINKED ISSUE #242: [BugBash]Dropdown should be hidden in case of No Response from API
image
Investing Ideas dropdowns are driven from APIs. Since APIs are not responding. DropDown should be hidden in that.

### PR DESCRIPTION
**Pull request by anagarwa**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #242 

Test URLs:
- Before: https://main--icicidirect--aemsites.hlx.live/research/equity
- After:  https://dropdown-fix--icicidirect--aemsites.hlx.live/research/equity

### CODE REVIEW

File: blocks/multi-panel-carousel/multi-panel-carousel.js [hunk 1]
```diff
@@ -560,7 +561,9 @@ async function generateDropDowns(block, type, marginActions) {
             count += 1;
           });
         }
-        addingDynamicDropDowns(block, type, restructuredData, marginActions);
+        if (restructuredData[dropDownDetails.dropdownType].length > 1) {
```
Comment (sdmcraft) [inline blocks/multi-panel-carousel/multi-panel-carousel.js:564]: Do we need any null safety here?

**Review by sdmcraft — APPROVED** [review]

**Review by JiangLong2019 — APPROVED** [review]

File: blocks/multi-panel-carousel/multi-panel-carousel.js (hunk 1 above)
Comment (anagarwa) [reply blocks/multi-panel-carousel/multi-panel-carousel.js:564]: @sdmcraft there will always be some value in this https://github.com/aemsites/icicidirect/pull/255/files#diff-df1b2d463c6833ad8072b28c5a30afb20ba6675ffa4fad33cc4a1e287b7cfe1fL546. So no need for null check
