### PR TITLE
fix: adding adobe dtm script

### LINKED ISSUE #88: Add Adobe DTM

### PR DESCRIPTION
**Pull request by anagarwa**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #88 88

Test URLs:
- Before: https://main--icicidirect--aemsites.hlx.live/research/equity
- After: https://adobedtm--icicidirect--aemsites.hlx.live/research/equity

- [ ] New Blocks introduced in this PR
      If yes, please provide details below

Block Name    | Documentation
------------- | -------------
 For e.g. carousel | [doc-link](https://main--icicidirect--aemsites.hlx.page/tools/sidekick/library.html?plugin=blocks&path=/sidekick/blocks/carousel&index=0)

### CODE REVIEW

File: scripts/delayed.js [hunk 1]
```diff
@@ -5,3 +5,5 @@ import { loadScript, sampleRUM } from './aem.js';
 sampleRUM('cwv');
 
 loadScript('https://icici-securities.allincall.in/files/deploy/embed_chatbot_11.js?version=1.1');
+
+loadScript('https://assets.adobedtm.com/64c36731dbac/390f7bab5b74/launch-285ee83071cc-development.min.js', { async: true });
```
Comment (sdmcraft) [inline scripts/delayed.js:9]: We need to add environment check to have appropriate script load. [Please refer this](https://github.com/sunstar-foundation/sunstar-foundation/blob/8c18978591b1caaef7c6b3696f671abca5c3f52e/scripts/delayed.js#L9-L16)

File: scripts/delayed.js [hunk 2]
```diff
@@ -4,5 +4,22 @@ import { loadScript, sampleRUM } from './aem.js';
 // Core Web Vitals RUM collection
 sampleRUM('cwv');
 
+function getEnvType(hostname = window.location.hostname) {
```
Comment (sdmcraft) [inline scripts/delayed.js:7]: `icicidirect.com` and `www.icicidirect.com` should also be considered. Probably we can map them to `prod`

File: scripts/delayed.js [hunk 3]
```diff
@@ -4,5 +4,22 @@ import { loadScript, sampleRUM } from './aem.js';
...
+}
+
 loadScript('https://icici-securities.allincall.in/files/deploy/embed_chatbot_11.js?version=1.1');
 loadScript('/scripts/cookie-script.js');
+
+(function loadAdobeLaunch() {
+  const adobeLaunchSrc = {
+    dev: 'https://assets.adobedtm.com/64c36731dbac/390f7bab5b74/launch-285ee83071cc-development.min.js',
+    preview: 'https://assets.adobedtm.com/64c36731dbac/390f7bab5b74/launch-285ee83071cc-development.min.js',
+    live: 'https://assets.adobedtm.com/64c36731dbac/390f7bab5b74/launch-285ee83071cc-development.min.js',
```
Comment (sdmcraft) [inline scripts/delayed.js:22]: Also add `prod` as specified in the previous comment.

**Review by sdmcraft — APPROVED** [review]
