### PR TITLE
Issue-139: Fix social share dialog issues

### LINKED ISSUE #139: Enhancement of social share modal
1. Prevent the scroll up/down when modal is open.

https://github.com/aemsites/icicidirect/assets/57093988/cded08c9-4f25-448a-a8c8-d01e8d04d729

2. When modal is open, it can be closed by clicking the X button and the dark gray area where is outside of dialog.

### LINKED ISSUE #150: Social share backdrop is not visible on safari
1. Social share backdrop is not visible on safari and iphone
2. CSS is broken in safari

image

### PR DESCRIPTION
**Pull request by yugandhar02**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #139
Fix #150 

Test URLs:
- Before: https://main--icicidirect--aemsites.hlx.live/research/equity
- After: https://issue-139--icicidirect--aemsites.hlx.live/research/equity

This PR fixes
1. Dialog is not closed when clicked on backdrop outside dialog
2. Background page scrolling when dialog is visible
3. Backdrop is not visible in safari and iphone.
4. Some CSS not working in safari due to syntax issue in styles.css

Background scrolling issue can be fixed using pure css solution as well but `:has` is not widely supported 
i.e. 
`
body:has(dialog[open]) {
    overflow: hidden;
}
`
So we will have to rely on javascript to set `modal-open` class on body element.
This doesn't fix all the issues. e.g. There could be more scrolling containers.
Reference for more details: https://github.com/whatwg/html/issues/7732

I have tested the fix on Chrome, Firefox, Safari and iPhone

### CODE REVIEW

File: scripts/social-utils.js [hunk 1]
```diff
@@ -2,6 +2,18 @@ import { fetchPlaceholders } from './aem.js';
 
 let isSocialShareDialogInitializing = false;
 
+function handleBodyScrollOnModalOpen() {
+  if (!document.body.classList.contains('modal-open')) {
+    document.body.classList.add('modal-open');
```
Comment (JiangLong2019) [inline scripts/social-utils.js:7]: Maybe using `toggle` will be more efficient

Comment (yugandhar02) [reply scripts/social-utils.js:7]: Sure. will consider that

Comment (yugandhar02) [reply scripts/social-utils.js:7]: I do agree.
But this is more robust and doesn't assume initial state.
But I don't see much issues using toggle in this case so will update the PR

Comment (yugandhar02) [reply scripts/social-utils.js:7]: Dialog close is getting handled two times since we listen to close event.
This will trigger toggle two times which results in a bug.
I have merged two functions in one.

**Review by sdmcraft — APPROVED** [review]

**Review by JiangLong2019 — APPROVED** [review]
