### PR TITLE
fix: updating market commentary to use APIs

### LINKED ISSUE #151: Integrate Market Commentary with APIs

### PR DESCRIPTION
**Pull request by anagarwa**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #151

Test URLs:
- Before: https://main--icicidirect--aemsites.hlx.live/research/equity
- After: https://marketcomapi--icicidirect--aemsites.hlx.live/research/equity

### CODE REVIEW

File: blocks/market-commentary/market-commentary.js [hunk 1]
```diff
@@ -32,7 +37,7 @@ function createMarketCommentaryCard(cardData, placeholders) {
       { class: 'footer-row' },
       span({ class: 'footer-circle' }),
     ),
-    div({ class: 'footer-time' }, footerTimeText),
+    div({ class: 'footer-time' }, NEWS_TIME),
```
Comment (JiangLong2019) [inline blocks/market-commentary/market-commentary.js:40]: I didn't get a chance to use the div() method. Just wondering, when the value such as `NEWS_TIME` is empty, will it still generate a div without content?

**Review by JiangLong2019 — APPROVED** [review]

File: blocks/market-commentary/market-commentary.js (hunk 1 above)
Comment (anagarwa) [reply blocks/market-commentary/market-commentary.js:40]: @JiangLong2019 yes
